### ISSUE TITLE
Core: Reorganize modules and isolate Zinc

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2218]
Motivation:
- Zinc always lag behind Scala library major releases. Typical lag is 6 months-1year. The reason is sbt is capable of running with an old Scala version, yet build with a recent one, as it has different classloaders and classpaths for running and compiling. The consequence is that we have no visibility on when we'll be able to upgrade to Scala 2.11 (released april 2014).
- Current module organization results is Zinc being shipped by every launcher, even the ones that don't need it (sbt plugin, IDE project).

Modifications:
- We have to change modules organization and have only launchers that depend on Zinc ship it: bundle + maven (+ gradle ?) plugin.
- We have to clean up our code so that we don't depend on scala-compiler except in the Zinc module. Most common dependency is `Path`.
- We have to introduce isolated classpaths/classloaders for running Gatling/compiling Simulations on Scala 2.11 vs running Zinc:
  - bundle: We would probably have to introduce distinct folders: libs, scala210 (library + compiler), scala211(library only) and compute differents classpaths
  - maven plugin: We could maybe have:
    - the plugin depend on Scala 2.10 compiler, so we can run Zinc from this ClassLoader
    - the project depend on Scala 2.11
- [x] Remove all references to scala-compiler/scala-reflect classes https://github.com/gatling/gatling/issues/2288
- [x] Move ZincCompiler to its own module, rewrite it in Java https://github.com/gatling/gatling/issues/2289
- [x] Modify the bundle construction to put Zinc libs and Gatling libs in separate folders https://github.com/gatling/gatling/issues/2290
