### ISSUE TITLE
Doc: Document 2.1 migration

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2368]
- [x] Single HttpRequestBuilder class as form features are available for all methods, see #2366, closed by 303c61d
- [x] `request-bodies` becomes `bodies`, see #2073, closed by dc487ff
- [x] update bundle links on Sonatype, as it now has a dedicated module
- [x] percentile configuration changes, closed by dc487ff
- [x] throttle behavior change, see #2415, closed by 0b30046
- [x] deprecated `dontValidate` was dropped, closed by 4f0b2ae
- [x] deprecated `baseHeaders` was dropped, closed by 11d5a97
- [x] bundle structure change
- [x] archetype generated project migration
- [x] test-framework/SBT plugin artifact id/versionning changes
