### ISSUE TITLE
Doc: Migration guide for 2.2

### ISSUE THREAD

**Issue by pdalpra** [gatling/gatling#2504]
- [x] `ELFileBody` renamed into `ElFileBody`
- [x] #2468: Use HOCON arrays -> impact on `writers`, `httpsEnabledProtocols` and `httpsEnabledCipherSuites`
- [x] #2507: `connection` was renamed into `connectionHeader`
- [x] #2534: document the new SBT's plugin `generateReports` task
- [x] #2576: changed normal pause distribution
- [x] #2729 drop `Cookie.withExpires`, use withMaxAge
- [x] #2755 Drop latency charts and check
- [x] #2816 sbt commands: `gatling:test` instead of `test`
- [x] #2900 `doIf(actual, expected)` renamed into `doIfEquals`
